# For additional information about this config file see:
# https://github.com/VEuPathDB/util-user-dataset-handler-server
service-name: BIOM Format Handler
command:
  # "/app" comes from the working directory configured in the Dockerfile
  # The rest of the path references the directory structure of the
  # VEuPathDB/EuPathGalaxy github repository.
  executable: /opt/handler/bin/exportBiomToEuPathDB
  args:
    # 1. dataset name
    - <<ds-name>>
    # 2. dataset summary
    - <<ds-summary>>
    # 3. dataset description
    - <<ds-description>>
    # 4. dataset uploader id
    - <<ds-user-id>>
    # 5. output file (ignored)
    - html.html
    # 6. Dataset origin
    - <<ds-origin>>
    # 7. dataset file path
    - <<input-files[0]>>
file-types:
  - .biom
