# For additional information about this config file see:
# https://github.com/VEuPathDB/util-user-dataset-handler-server
service-name: BIOM Format Handler
command:
  # "/app" comes from the working directory configured in the Dockerfile
  # The rest of the path references the directory structure of the
  # VEuPathDB/EuPathGalaxy github repository.
  executable: /opt/handler/bin/exportBiomToEuPathDB
  args:
    # dataset name
    - <<ds-name>>
    # dataset summary
    - <<ds-summary>>
    # dataset description
    - <<ds-description>>
    # dataset uploader "email" (for compatibility purposes, not a real email address)
    # <anything>.<wdk user id>@veupathdb.org
    - <<ds-user-email>>
    # path to XML lib
    - ""
    # output file (ignored)
    - html.html
    # ???
    - ""
    # dataset file path
    - <<input-files[0]>>
file-types:
  - .biom
